services:
  # Go/Echo アプリケーションサービス
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      # ホストの1323ポートをコンテナの1323ポートにマッピング
      - "1323:1323"
    volumes:
      # ホストのカレントディレクトリをコンテナの/appにマッピング（ホットリロードのため）
      - .:/app
    env_file:
      # .envファイルから環境変数を読み込む
      - .env
    depends_on:
      # dbサービスが起動してからappサービスを起動する
      - db

  # PostgreSQL データベースサービス
  db:
    image: postgres:16-alpine
    container_name: pg-16
    ports:
      # ホストの5432ポートをコンテナの5432ポートにマッピング
      # (ホストのDBクライアントから接続する際に使用)
      - "5432:5432"
    volumes:
      # DBのデータを永続化するためのボリューム
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env

# Dockerが管理する名前付きボリュームの定義
volumes:
  db-data:
